function [dPdX] = dpdx(N, Pressure, q_Plate, x);
%
% this function gives the 6N x 6N matrix dp/dx of Eq. 4 in KPD for the case
% of a lateral membrane force on the exterior paritlcles produced by
% a chamber pressure
%
% particle body force p = Pressure * cross product of the two side vectors (a X b)
%
  dPdX = zeros(6*N,6*N);
%
  for p = 1:N
    Rows = 3*(p-1) + [1:3];
%
    for plate = 1:4
      if q_Plate(p, plate, 1) ~= 0
        a = x(q_Plate(p, plate, 1), :) - x(p,:);
        b = x(q_Plate(p, plate, 2), :) - x(p,:);
%
%       unit normal vector of plate
        n = Cross_Product(a)*b';
        n = (1/sqrt(sum(n.^2))) * n;
%
        Columns = [3*(p - 1) + [1:3], ...
                   3*(q_Plate(p, plate, 1) - 1) + [1:3]]; % q for vector a
        dPdX(Rows, Columns) = dPdX(Rows, Columns) ...
                              +  ...
                              n * n' ...
                              * [ ...
                                     0, -b(3), b(2),     0,  b(3), -b(2); ...
                                  b(3),    0, -b(1), -b(3),     0,  b(1); ...
                                 -b(2),  b(1),    0,  b(2), -b(1),    0   ...
                                ];
%
        Columns = [3*(p - 1) + [1:3], ...
                   3*(q_Plate(p, plate, 2) - 1) + [1:3]]; % q for vector b
        dPdX(Rows, Columns) = dPdX(Rows, Columns) ...
                              +  ...
                              n * n' ...
                              * [ ...
                                     0,  a(3), -a(2),     0, -a(3),  a(2); ...
                                 -a(3),    0,   a(1),  a(3),     0, -a(1); ...
                                  a(2), -a(1),     0, -a(2),  a(1),     0   ...
                                ];
        zzz = 0;
      end
    end
  end
%
% negative, because pressure acts inward. Factor 0.25, because only 1/4 of
% of the unit cell side contributes a corner's force
  dPdX = -0.25 * Pressure * dPdX;
