function [ next_x_near, x_next, a_k, v_k, w_k, z_k, z_b, ...
           Delta, d_count, memory, in_pivot, ...
           pathsearch_type, search_type_change, take_pg_step, mark_check, ...
           checkpointxN, checkpointzN, stop, restart] = ...
         NMS_func( ...
           n, l, u, f, Df, zwvt, infty, ...
           d_count, take_pg_step, ...
           a_k, v_k, w_k, z_k, z_b, ...
           z_k_N, x_k_N, v_k_N, w_k_N, ...
           Delta, Delta0, next_x_near, x_next, memory, Ref, in_pivot, ...
           max_d_count, sigma_NMS, pg_search_type, max_m_alpha_pg, ...
           max_m_alpha_w, major, ...
           mark_check, bestpoint, checkpointx, checkpointz, ...
           checkpointxN, checkpointzN, search_type_change, ...
           pathsearch_type, display_depth, stop, restart, deltachange)
%
% An adaptation of the NMS.m file of Stefan Schmelzer, in the
% form of an Octave function.  The header information of Stefan Schmelzer
% is given below.  This adaptation is free software: you can redistribute
% it and/or modify it under the terms of the GNU General Public License as
% published by the Free Software Foundation, either version 3 of the License,
% or (at your option) any later version.
%
% Matthew R. Kuhn
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NMS: Non-Monotone Stabilization scheme
% Copyright (C) 2012 Stefan Schmelzer
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% This file is part of COMPASS.

% COMPASS is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.

% COMPASS is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
  
% You should have received a copy of the GNU General Public License
% along with COMPASS.  If not, see <http://www.gnu.org/licenses/>.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%
% Comments on this file: 

% descent or distance criteria are used to check whether x_k_N is
% accepted as the new iterate. If it is not, a search is performed in 
% order to determine an acceptable point.  

% possible steps:
% d-steps, m-steps, watchdog steps, projected gradient steps
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



if take_pg_step == 1

  %%%%%%%%%%
% pg_step
% Kuhn: change pg_step.m script to pg_step_func.m function
  % Returns z_k, new checkpoint
  [ a_k, v_k, w_k, z_k, z_b, ...
    stop, restart, next_x_near, x_next, ...
    search_type_change, memory, in_pivot] = ...
  pg_step_func( ...
    n, bestpoint, l, u, f, Df, zwvt, infty, ...
    a_k, v_k, w_k, z_k, z_b, ...
    sigma_NMS, pg_search_type, max_m_alpha_pg, ...
    display_depth, stop, restart, next_x_near, ...
    search_type_change, memory, in_pivot);
  %%%%%%%%%%%%%%%%%%

  take_pg_step = 0;
  d_count = 0;
  Delta = Delta0;
  mark_check = major;

else 

  if (norm(z_k_N - z_k) <= Delta) && (d_count <= max_d_count) %distance criterion

    if (Psi(z_k_N,l,u,f,infty) <= Ref + Ref*0.1) % weak descent criterion

      %%%%%%%%%
%     d_step
      % Returns z_k, x_k, w_k and v_k
% Kuhn: change d_step.m script to d_step_func.m function
      [z_k, x_k, v_k, w_k] = ...
        d_step_func(z_k_N, x_k_N, v_k_N, w_k_N, display_depth);
      %%%%%%%%%%%

      d_count = d_count+1;
      Delta = Delta-deltachange;
    else
 
      %%%%%%%%%%%%%%%
%     watchdog_step
      % Returns z_k, new checkpoint
% Kuhn: change watchdog_step.m script to watchdog_step_func.m function
      [ a_k, v_k, w_k, z_k, z_b, ...
        stop, restart, next_x_near, x_next, ...
        search_type_change, memory, in_pivot, ...
        pathsearch_type] = ...
      watchdog_step_func( ...
        n, l, u, f, Df, infty, ...
        bestpoint, zwvt, x_next, ...
        a_k, v_k, w_k, z_k, z_b, memory, in_pivot, ...
        checkpointx, checkpointz, ...
        checkpointxN, checkpointzN, search_type_change, ...
        Ref, sigma_NMS, pg_search_type, ...
        pathsearch_type, display_depth, max_m_alpha_w, ...
        max_m_alpha_pg, stop, restart, ...
        next_x_near);
      %%%%%%%%%%%%%%%%%%%

      d_count = 0;
      Delta = Delta0;
      mark_check = major;
    end

  else

    %%%%%%%%%%%%%
%   m_step
    % Returns z_k, new checkpoint
% Kuhn: change m_step.m script to m_step_func.m function
    [ a_k, v_k, w_k, z_k, z_b, ...
      memory, in_pivot, ...
      stop, restart, next_x_near, x_next, ...
      pathsearch_type, search_type_change] = ...
    m_step_func( ...
      n, a_k, v_k, w_k, z_k, z_b, ...
      z_k_N, l, u, f, Df, infty, ...
      checkpointx, checkpointz, ...
      checkpointxN, checkpointzN, search_type_change, ...
      Ref, sigma_NMS, memory, in_pivot, ...
      pg_search_type, pathsearch_type, display_depth, max_m_alpha_w, ...
      max_m_alpha_pg, stop, restart, x_next, next_x_near);
    %%%%%%%%%%%%%%%%%

    d_count = 0;
    Delta = Delta0;
    mark_check = major;
  end

end


% PARENTFILE: majoriter.m
