#!/bin/bash
#
# Test for the input ".gnu" file with or without the extension
if test -f $1".gnu"
  then
    FILE=$1
  else
    SUFFIX=$(echo $1 | cut -c$(expr $(expr length $1) - 3)-)
    echo $SUFFIX
    if test $SUFFIX=".gnu"
      then
      FILE=$(echo $1 | cut -c1-$(expr $(expr length $1) - 4))
      echo $FILE
    fi
fi
#
cat /home/kuhn/bin/Common1.gnu $FILE.gnu > dummy.gnu
gnuplot dummy.gnu
#/opt/gnuplot-5.2.0/src/gnuplot dummy.gnu
#
# Test for the file 'MakeFig.tex'
if test -f "MakeFig.tex"
  then
    echo Found MakeFig.tex
  else
    cp ~/bin/MakeFig.tex .
  fi
#
latex MakeFig << EOF
dummy
EOF
#dvips -o dummy2.ps MakeFig
#psfixbb -o $FILE'.eps' dummy2.ps
#ps2eps -f dummy2.ps
#mv dummy2.eps $FILE'.eps'
#echo
#echo gv --media=bbox $FILE'.eps &'
#echo
#
# Check whether ghostview is displaying the eps files
#TESTEPS=$(ps au | grep "gv --media=bbox $FILE.eps")
#
#if test `expr length "$TESTEPS"` -ne 0; then
#    echo ghostview is running
#  else
#    gv --media=bbox $FILE'.eps' &
#fi
#
#epspdf --bbox $FILE'.eps'
#epspdf $FILE'.eps'
#/opt/epspdf/epspdf.rb $FILE'.eps'
#epstopdf $FILE'.eps'
dvipdf MakeFig dummy2.pdf
pdfcrop dummy2.pdf $FILE'.pdf'
