page_screen_output(0);
%page_output_immediately(1);
%
  clear
%
  global M_hat q_hat
%
% functions for use in the Octave function sqp() for sequential quadratic
% programming
  sqp_functions;
  sqp_bundles;
%
%%Mount_Point = '~/MyDrive/Kuhn_in_Progress/';
% Mount_Point = '~/GoogleDrive/Kuhn_in_Progress/';
% Mount_Point = '~/SSHFS/';
  Mount_Point = '../';
%
% add path to utility m-files
%%addpath('~/GoogleDrive/mfiles/');
  addpath('../mfiles/');
  addpath('../mfiles2/');
  addpath(cstrcat(Mount_Point, '../Instability/Octave/'));
%
% parameters
%
% the code works with both Octave and Matlab.  Create the following
% two constants. The two softwares have subtle differences.
  Octave = 1; Matlab = 2;
%
% select the software system here
  System = Octave;
%
% threshold distance between two particles that will place them into 
% a linked list of near-neighbors (i.e., a list of candidate contacts).
% "Sep" is a fraction of the average particle size (e.g., radius)
% Sep = 0.05;
%
% ratio by which the numbers of bins are increased in each dimension.
% Normally this should be 1.  However, if there are relatively few of the
% largest particles compared with the number of small particles, then
% it becomes less likely that two of the largest particles will be in
% adjacent bins, so that BinRatio can be made larger
  BinRatio = 1;
%
% whether to scale the size of the assembly:
%    [] or 0,  do not scale.  Use the input values
%    > 0,      scale by the value of scale_sizes
%    < 0,      scale the assembly so that mean(Size) = abs(scale_sizes)
  scale_sizes = -1.0;
%
% one can arbitrarily increase the radii of cuvatures of the particles'
% surfaces at their contacts. If factor is [], 0, 1, or negative, the factor
% is 1
  CurveFactor = 1;
%
% whether to compute and store the [M_alt] and [q_alt} for a system with
% no constraints on dxcell, for post-processing
  if_Output_File_alt = 0;
%
% minimum number of contacts for a particle to be included in the analysis
% Min_Coord_No = 2;
%
% when a Problem 2 LCP is being solved, the maximum M_lambda for which the
% slower full enumeration method is used
% M_lambda_max_enumerate = 22;
%
% problem types, as described in the paper XXX.  Choose 1 or 2. (Problem 3
% is solved in the same manner as Problem 2.)
% Problem = 1; % Try solving the matrix equations for all stiffness matrices
  Problem = 2; % Treat the problem as a linear complementarity problem (LCP)
%
% maximum number of lambdas per contact in the various contact models
  m_lambdas = 5;
%
% lambda_tolerance = an kx1 vector that gives the tolerances associated
% with the activation of possible slip conditions (lambdas).  For a 
% simple linear-frictional contact, k=1 and the lambda_tolerance is a scalar.
% For contact models with multiple slip mechanisms (e.g., both sliding and
% rotational friction), lambda_tolerance will be a vector
% lambda_tolerance = [0.00002];
%
% maximum devation in controlled stresses from their target values before
% corrective action is taken
% Max_stress_deviation = 0.02e-3;
% Max_stress_deviation = inf;
%
% maximum average force imbalance on particles before corrective action is
% taken
% Max_b_p = 3.0e-6;
% Max_b_p = inf;
%
% maximum repetitions at constant stress & strain during corrective action
% Max_Repetitions = 10;
%
% a spring stiffness can be included with the periodic "walls".  If this is
% not wanted leave the values as zero
% K_walls = zeros(6,6); % Note, there are 6 dxcell components
% K_walls(2,2) = 0.1;
%
% if K_walls is non-zero, then the stress will drift, so nullify the
% Max_stress_deviation criterion
% if ~all(all(~K_walls))
%   Max_stress_deviation = inf;
% end
% 
%
% other parameters
  Approx_Singular_Matrix = 0;
  Approx_Singular_Matrix = 1e6;
  Cond_numbers = 0;
%
%
% List of Octave's Methods that can be used to solve the LCP, and the folder
% locations that contain the library
  qpOctave = 1; % Octave's qp() solver
  Quadprog = 2; % Octave's quadprog() solver
  COMPASS =  3; % COMPASS solver
  Murty =    4; % LCP_enumerate() solver
  Yuval =    5; % Mathworks code by Yuval
  Almqvist = 6; % Mathworks code by Andreas Almqvist
  CompEcon = 7; % Paul L. Fackler & Mario J. Miranda
%
%
% initial guess for LCP solver, or enter the empty "[]" value, for zeros
  x0 = [];
%
% folder that contains the RunFiles, which give the simulation conditions:
% (1) contact properties, mu = coefficient of friction; k = normal stiffness;
% (2) loading sequence
  RunFile_Directory = cstrcat(Mount_Point, 'Instability/RunFiles/');
%
% folder that contains the Dfiles, which provide the initial positions of
% the particles.  Don't forget to end with a "/" or "\"
  DFile_Directory = cstrcat(Mount_Point, 'Instability/Assemblies/');
%
% folder that will contain the output files. Don't forget to end with a "/" 
% or "\"
  Output_Directory = cstrcat(Mount_Point, 'Instability/Output/');
%
% path to the directory that holds all of the libraries
  LibrariesPath = cstrcat(Mount_Point, 'LCP/Libraries/');
%
% add the path for the enumerative "Murty" method
  addpath(cstrcat(LibrariesPath,'Murty'));
%
% specify the conditions and loading path for the simulation
  RunFile = 'Biaxial_Comp_k16'; % runs full enumerative LCP analysis
% RunFile = 'Biaxial_Comp_k22'; % runs QP analysis
%
% uncomment the Dfile that gives the initial positions of particles 
% in the assembly
% DFile = 'Dcircls_49_a-12';   % 49 disks, dense, ~98 contacts,
%                              %   ~-1.8e-3 stress
%                              %   ~/SSHFS/Scatter/Assemblies_49_a/
% DFile = 'Dcircls_49_a-38';   % 49 disks, dense, ~90 contacts,
%                              %   ~-3.3e-4 stress
%                              %   ~/SSHFS/Scatter/Assemblies_49_a/
% DFile = 'Dcircls_49_a-39';   % 49 disks, dense, ~95 contacts,
%                              %   ~-1.4e-3 stress
%                              %   ~/SSHFS/Scatter/Assemblies_49_a/
  DFile = 'Dcircls_49_a-57';   % 49 disks, dense, ~92 contacts,
%                              %   ~-1.25e-3 stress
%                              %   ~/SSHFS/Scatter/Assemblies_49_a/
% DFile = 'Dcircls_64_a-16';   % 64 disks, dense, ~125 contacts,
%                              %   ~-8.5e-4 stress
%                              %   ~/SSHFS/Scatter/Assemblies_64_a/
% DFile = 'Dcircls_64_a-1';    % 64 disks, dense, ~125 contacts,
%                              %   ~-1.1e-3 stress
%                              %   ~/SSHFS/Scatter/Assemblies_64_a/
%                              % has large initial deviator stress
% DFile = 'Dcircls_64_a-16';   % 64 disks, dense, ~125 contacts,
%                              %   ~-8.5e-4 stress
%                              %   ~/SSHFS/Scatter/Assemblies_64_a/
% DFile = 'Dcircls_64_a-27';   % 64 disks, dense, ~136 contacts,
%                              %   ~-1.6e-3 stress
%                              %   ~/SSHFS/Scatter/Assemblies_64_a/
% DFile = 'Dcircls_256_b-42';  % 256 disks, very loose, ~35 contacts,
                               %   ~-2.0e-7 stress
                               %   ~/SSHFS/Scatter/Assemblies_256_b/
% DFile = 'Dcircls_256_b-18';  % 256 disks, loose, ~250 contacts,
                               %   ~-4.0e-6 stress
                               %   ~/SSHFS/Scatter/Assemblies_256_b/
% DFile = 'Dcircls_256_b-48';  % 256 disks, medium, ~344 contacts,
                               %   ~-1.0e-5 stress
                               %   ~/SSHFS/Scatter/Assemblies_256_b/
%%DFile = 'Dcircls_256_a-100'; % 256 disks, dense, ~502 contacts,
                               %   ~-7.2e-4 stress
                               %   ~/SSHFS/Scatter/Assemblies_256_a/
%--------------
% DFile = 'DSpheres-512-a-18'; % 512 spheres, very loose, ~336 contacts,
                               %   ~-4.0e-6 stress
                               %   ~/SSHFS/Assemblies3/Spheres-512-a/
% DFile = 'DSpheres-512-a-3';  % 512 spheres, loose, ~530 contacts,
                               %   ~-1.0e-5 stress
                               %   ~/SSHFS/Assemblies3/Spheres-512-a/
% DFile = 'DSpheres-512-a-20'; % 512 spheres, medium, ~1068 contacts,
                               %   ~-7.5e-5 stress
                               %   ~/SSHFS/Assemblies3/Spheres-512-a/
% DFile = 'DSpheres-512-c-3';  % 512 spheres, dense, ~1404 contacts, 
                               %   ~-4.4e-4 stress
                               %   ~/SSHFS/Assemblies3/Spheres-512-c/
%---------------
% DFile = 'DSpheres-4096-c-1';  % 4096 spheres, dense
% DFile = 'DNobbies-256-5-0.7-0.01-a-100';
% DFile = 'DCreate_Dfile_Isotropic_c_10kPa-Bumpies-6400-6-060-08-074_File_11'; BinRatio = 2;
%
% basic particle shapes
  [Circle, Oval, Ellipse, Sphere, Ovoid, Nobby, Bumpy] = Shapes3();
%
% read a RunFile, which gives the input values of k, mu, alpha.  It also
% gives the loading sequence
  [ algori, iinteg, ncownt, iout, ...
    istart, iend, idef, iupdtm, icirct, imodel, nplatn, nloop1, ...
    k, alpha, mu, frictw, rho, sep, pcrit, ...
    xseed, rmsvel, pdif, tmax, A_1, dt, ...
    ivers, iexact, isub, gravty, ifree, rfree, ...
    icontr, defrat, igoal, krotat, finalv, ipts, ...
    idump, iflexc, imicro, ibodyf, defdot, ipts2, iplot, ...
    Only_Fast_Method, Type_Constraint, Min_Coord_No, ...
    Max_Repetitions, M_lambda_max_enumerate, Sep, lambda_tolerance, ...
    Max_stress_deviation, Max_b_p, K_walls, lambda_threshold, ...
    if_Inst_Output, Choose_MaxEnt_Path] = ...
  Read_LCP_RunFile(cstrcat(RunFile_Directory, RunFile));
%
% create the initial assembly, by reading a Dfile of particles contained
% within periodic boundaries. Also, do various initializations
  [ Shape, idim, xcell, xcell_init, N, Size, u, Qp, ...
    satrad, cenrad, cirrad, njoin, s_rad, b_rad, xlocal, ...
    rmax, ravg, periodic_directions, Contact_List, ...
    def, istep, V_pq, C_pq, f_pq, m_pq, df_pq, dm_pq, n_pq, r_pq_p, ...
    Overlap_pq, k_pq, Map_p_Rel_to_All, iupdat, I, J, ...
    Time, istepo, icont, iconto, init_output, Output_Cell_Array, ...
    Output_Instab_Array, ...
    M_lambda, M_hat, q_hat, lambda, last_Save_Time, last_Write_Time, ...
    Method_used, is_Soln, Lambda, DegenSoln, DegenMatrix, ...
    du, b_p_Rel, RCond_BD, iOutput, File_Path, File_Path_Instab, ...
    Headings, Headings_Instab, ...
    Repetitions, Time_to_Stop, Path_Stability, ...
    R, Prr, Pnrr, P_L, P_Lperp, C_MP_inv, dTime, stress, ...
    H_x, H_lambda, Q_x, Q_lambda, H_stress_x, H_stress_lambda, ...
    C_wo_dxcell, ...
    H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, ...
    map_lambda_to_pq_and_qp, u_update, xcell_update,  ...
    Threshold_separation, nbins, bin_list, surround_bins, dgamma, ...
    File_Path_alt, Output_Cell_Array_alt, Headings_alt, M_alt, q_alt] = ...
  Create_Assembly_D(DFile_Directory, DFile, scale_sizes);
%
% get the initial loading parameters
  [ istep, icont, ddef, ddefm, dstress, stress_target, Reset_target_stress, ...
    istop, increment, max_increments, nStress, iStress, ...
    lap_Time, start_Time] = ...
  Control_alt(istep, icontr, icont, defrat, igoal, finalv, idim, ...
              I, J, Time);
%
  disp(RunFile)
  disp(DFile)
%
% the main loop for advancing the loading process
  while istep <= size(icontr,1) + 1
%
%   number of deformation steps since this start of the simulation
    Time_prev = Time;
    Time = Time + 1;
%
%   number of increments within the control period
    increment = increment + 1;
%
%   determine whether to conduct a new near-neighbor search
%   [lupdate, iupdat] = Update_Near_Neighbors(iupdat, iupdtm, istep);
    [ lupdate, iupdat] = ...
    Update_Near_Neighbors2( ...
      iupdat, iupdtm, istep, Time, idim, ...
      u, u_update, xcell, xcell_update, Threshold_separation, ...
      nbins, bin_list, surround_bins);
%
    if lupdate
%     find near-neighbor lists of candidates for particle-pairs contacts.
%     Near_list_2 is a M_near x 4 array.  In each row, [p, q, p_join, q_join]
      [ Near_list_2, u_update, xcell_update, nbins, bin_list, surround_bins, ...
        Threshold_separation, iupdat] = ...
      Near_Neighbors(N, Shape, Size, u, Qp, s_rad, b_rad, ...
                     xlocal, xcell, periodic_directions, rmax, ravg, njoin, ...
                     Sep, BinRatio);
    end
%
%   find and characterize the contacts
    [ Contact_List, M, x, V_pq, C_pq, r_pq_p, r_pq_q, n_pq, ...
      Overlap_pq, rho_pq, V_pq_old, C_pq_old, Map_p_Rel_to_All_old, ...
      K_pq, K_inv, mu_pq, k_pq, alpha_pq, FM_model_pq, Coord_Number, idim] = ...
    Contacts_Find( ...
      N, Shape, Size, u, Qp, s_rad, b_rad, xlocal, ...
      xcell, periodic_directions, Near_list_2, Contact_List, ...
      mu, k, alpha, CurveFactor, V_pq, C_pq, Map_p_Rel_to_All);
%
%   cull the particles (and contacts) for those with at least Min_Coord_No
%   contacts. Note that the some previous arrays are replaced with new 
%   (renamed) ones
    [ N_All, p_All, N_Rel, p_Rel, N_NonRel, p_NonRel, ...
        Map_p_Rel_to_All, Map_p_All_to_Rel, ...
        Map_p_NonRel_to_All, Map_p_All_to_NonRel, ...
      M_All, pq_All, M_Rel, pq_Rel, M_NonRel, pq_NonRel, ...
        Map_pq_Rel_to_All, Map_pq_NonRel_to_All, ...
      x_Rel, V_pq, C_pq, r_pq_p, r_pq_q, n_pq, Overlap_pq, ...
      rho_pq, K_pq, K_inv, mu_pq, k_pq, alpha_pq, FM_model_pq] = ...
    Map_Relevant_Particles( ...
      N, M, Min_Coord_No, V_pq, C_pq, Coord_Number, ...
      x, r_pq_p, r_pq_q, n_pq, Overlap_pq, Map_p_Rel_to_All, ...
      rho_pq, K_pq, K_inv, mu_pq, k_pq, alpha_pq, FM_model_pq);
%
%   find the new contact forces and the net forces and moments on the particles
    [ f_pq, m_pq, b_p_Rel, w_p_Rel, Warning] = ...
    Revise_Contact_Forces( ...
      N_Rel, M_Rel, f_pq, m_pq, df_pq, dm_pq, n_pq, ...
      r_pq_p, Overlap_pq, k_pq, V_pq, V_pq_old, ...
      C_pq, C_pq_old, Map_p_Rel_to_All, Map_p_Rel_to_All_old, ...
      FM_model_pq, mu_pq, Time);
%
%   create output cell array and write results to the array
    [ Output_Cell_Array, Headings, Output_Instab_Array, Headings_Instab, ...
      init_output, istepo, iconto, ...
      last_Save_Time, last_Write_Time, iOutput, File_Path, ...
      File_Path_Instab, ...
      File_Path_alt, Output_Cell_Array_alt, Headings_alt] = ...
    Output_alt( ...
      Output_Cell_Array, Headings, Output_Instab_Array, Headings_Instab, ...
      Time, istep, istepo, ...
      icont, iconto, idim, ipts, ipts2, ...
      xcell, xcell_init, V_pq, r_pq_p, f_pq, RCond_BD, u, du, ...
      M_lambda, M_hat, q_hat, lambda, last_Save_Time, last_Write_Time, ...
      Method_used, is_Soln, Lambda, DegenSoln, DegenMatrix, ...
      Path_Stability, if_Inst_Output, ...
      P_L, H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, ...
      C_wo_dxcell, H_x, H_lambda, Q_x, Q_lambda, ...
      RunFile, DFile, Output_Directory, init_output, iOutput, ...
      File_Path, File_Path_Instab, ...
      if_Output_File_alt, File_Path_alt, Output_Cell_Array_alt, ...
      Headings_alt, M_alt, q_alt, ...
      Warning, Time_to_Stop);
%
%   whether to terminate the simulation
    if Time_to_Stop
      break
    end
%
%   with periodic boundaries, we identify the contacts that "cross" the
%   boundaries and the direction of crossing
    [dxcell_pq] = ...
    Periodic_Boundaries(x_Rel, V_pq, xcell, idim, periodic_directions);
%
%   apply the net forces and moments on particles as external forces
    [dp] = External_Forces(N_Rel, b_p_Rel, w_p_Rel);
%
%   miscellaneous initializations
    [ Combinations, H_g4, c, f, dx_c, C, dc, ...
      R, Prr, Pnrr, other_parameters] = ...
    Misc_Initialization(N_Rel);
%
%   apply the prescribed deformation increments to find dxcell
    [ xcell, xcello, dxcell, def, defo, ddefm_apply, ...
      Vol, stress, stress_target, Reset_target_stress, Time, dTime, ...
      stress_targeto, dstress_apply, Repetitions] = ...
    Def_Stress_Increments( ...
      xcell, def, ddefm, r_pq_p, f_pq, stress, ...
      nStress, iStress, Reset_target_stress, stress_target, dstress, ...
      Time, Time_prev, b_p_Rel, is_Soln, I, J, idim, ...
      Max_stress_deviation, Max_b_p, Repetitions, Max_Repetitions);
%
%   these constraints prevent drifting of the assembly
    [ C, dc] = Deformation_Constraints(xcell, N_Rel, x_Rel, idim);
%
%   create the H and Q stiffness/consistency matrices of the individual contacts
    [ H_m_pq_x, H_g1_pq, H_g2_pq, H_g3_pq, B_pq, H_m_max, ...
      H_pq_lambda, Q_pq_x_all, Q_pq_lambda_all, ...
      k_lambdas_pq_all, lambdas_pq_all, S_pq_x_all, S_pq_lambda_all] = ...
    LCP3_Stiffness_Matrices_pq( ...
      r_pq_p, r_pq_q, n_pq, f_pq, m_pq, dxcell_pq, ...
      K_pq, K_inv, mu_pq, k_pq, alpha_pq, other_parameters, ...
      lambda_tolerance, FM_model_pq, m_lambdas);
%
%   assemble the 6Nx6N global stiffnesses H_g1, H_g2, H_g3 for the entire 
%   assembly, as with the "squiggles" in KPD Eqs. 28, 33, and 34.  On the other 
%   hand, the mechanical stiffness H_m will depend upon the particular 
%   combination of branches among the contacts (H_m will be assembled 
%   elsewhere).  We also assemble the global kinematics matrix "B" for 
%   the entire assembly, as this will be needed to test the yielding 
%   of the contacts (as in KPD Eqs. 19 and 86)
    [ H_x, H_m_x, H_g1, H_g2, H_g3, H_g1234, B, ...
      H_lambda, Q_x, Q_lambda, M_lambda, map_lambda_to_pq_and_qp_old, ...
      map_lambda_to_pq_and_qp, map_pq_to_qp, map_pq_to_lambdas] = ...
    LCP3_Assemble_H_Q_Matrices( ...
      V_pq, C_pq, H_m_pq_x, H_g1_pq, H_g2_pq, H_g3_pq, H_g4, ...
      B_pq, map_lambda_to_pq_and_qp, ...
      H_pq_lambda, Q_pq_x_all, Q_pq_lambda_all, ...
      k_lambdas_pq_all, lambdas_pq_all, ...
      N_Rel, FM_model_pq, lambda_tolerance, m_lambdas);
%
%   compute the H_sigma_x and H_sigma_lambda matrices, which will be
%   combined with other stiffnesses
    [ H_stress_x, H_stress_lambda, dstress_vec] = ...
    Stress_Constraints( ...
      N_Rel, icont, xcello, dxcell, nStress, iStress, ...
      Vol, stress, stress_target, V_pq, r_pq_p, n_pq, f_pq, ...
      K_pq, K_inv, B_pq, H_m_pq_x, ...
      M_lambda, H_pq_lambda, map_pq_to_lambdas, idim, I, J);
%
%   combine the "H" matrices for dx, dlambda, dxcell, dstress
    [ H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, ...
      dxcell_vec, dp_dstress] = ... 
    Combine_H_alt( ...
      H_x, H_lambda, H_stress_x, H_stress_lambda, Q_x, Q_lambda, ...
      dp, dstress_vec, dxcell);
%
%   prepare for 2D problems, by eliminating rows and columns from the
%   3D matrices
    [ H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, dp_dstress] = ...
    LCP3_Convert_2D_or_3D_alt( ...
      N_Rel, H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, dp_dstress, idim);
%
%   thus far, the "C" constraint matrix only prevents the assembly from
%   drifting.  Append to the C matrix with the constraints on cell deformation.
%   Also, convert to 2D, if needed
    [ C_w_dxcell, dc_w_dxcell, C_wo_dxcell, dc_wo_dxcell, ...
      C_wo_constr, dc_wo_constr] = ...
    C_constraints_alt(N_Rel, C, dc, dxcell_vec, iStress, idim);
%
%   find the projection matrices P_L and P_Lperp
    [ P_L, P_Lperp, C_MP_inv, ...
      P_L_wo_constr, P_Lperp_wo_constr, C_MP_inv_wo_constr] = ...
    LCP3_Projections_Types_II_III(C_w_dxcell, [], C_wo_constr);
%
%   a tiny tolerance value that will be used for testing eigenvalues,
%   determinants, etc.
    Tiny = 1e-9;
    Null_tol =  H_m_max * Tiny;
    S_tol = 10 * Tiny;
    Eig_tol = H_m_max * Tiny;
%
%   set up the LCP by finding M_hat and q_hat
    [ M_hat, q_hat, H_xx_BD_inv, RCond_BD, ...
      M_alt, q_alt, H_xx_BD_inv_wo_constr] = ...
    Setup_LCP_alt( ...
      H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, ...
      P_L, P_Lperp, C_MP_inv, dp_dstress, dc_w_dxcell, ...
      P_L_wo_constr, P_Lperp_wo_constr, C_MP_inv_wo_constr, dc_wo_constr);
%
%   look for the same sliding contacts as in the previous time step, so that
%   the previous "lambda" lambda values can be used as an initial guess in
%   finding the new lambda values
    isHeadStart = 1;
    [ lambda_try, n_intersect_lambda] = ...
    HeadStart( ...
      lambda, isHeadStart, ...
      Map_p_Rel_to_All_old, Map_p_Rel_to_All, ...
      V_pq_old, V_pq, C_pq_old, C_pq, ...
      map_lambda_to_pq_and_qp_old, map_lambda_to_pq_and_qp);
%
%   solve the LCP
    [ lambda, Lambda, fval, ...
      DegenSoln, IsolatedSoln, NonIsolated, ...
      ColCompetent, DegenMatrix, n_DegenMatrix, ...
      is_PD, is_NS, Method_used, is_Soln] = ...
    Solve_LCP_alt( ...
      M_hat, q_hat, x0, [], PHI, Hc, System, LibrariesPath, ...
      M_lambda_max_enumerate, Only_Fast_Method, ...
      lambda_try, n_intersect_lambda, 10*eps);
%
%   in the event of multiple solutions (bifurcation), select the "lambda"
%   solution that maximizes 2nd-order entropy. Note that "Lambda" contains
%   all of the solutions
    [ lambda] = ...
    MaxEnt_Path( ...
      Lambda, Choose_MaxEnt_Path, is_Soln, ...
      H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, ...
      H_xx_BD_inv, C_MP_inv, dxcell_vec, dp_dstress, dc_w_dxcell);
%
%   if the lambda values are too large, advance the time, deformation, 
%   and stress by fractional amounts
    [ Time, lambda, lambda_original, dp, dstress_vec, dc, dgamma, ...
      xcell, dxcell, dxcell_vec, def, stress_target] = ...
    Check_Lambda( ...
      lambda, lambda_threshold, ...
      Time, dTime, Time_prev, dp, dstress_vec, dc, dgamma, ...
      xcell, dxcell, xcello, dxcell_vec, def, defo, ddefm_apply, ...
      stress_target, stress_targeto, dstress_apply, nStress);
%
%   use the "lambda" solution to find dx, dy, dxcell, etc.; create the
%   Nx3 du and dtheta values; revise quaternions; and compute incremental
%   changes in contact forces, so that we can later compute any small
%   deviations from equilibrium
    [ du, u, dtheta, Qp, df_pq, dm_pq, dxcell, xcell, ...
      dy, dy_moment, dy2, dycell2, dxcell_vec, Path_Stability] = ...
    Process_Results_alt( ...
      N, N_Rel, Map_p_Rel_to_All, u, Qp, ...
      H_x_x, H_x_lambda, H_lambda_x, H_lambda_lambda, ...
      H_xx_BD_inv, C_MP_inv, dp_dstress, dc_w_dxcell, ...
      lambda, S_pq_x_all, S_pq_lambda_all, M_lambda, ...
      map_lambda_to_pq_and_qp, ...
      V_pq, B_pq, FM_model_pq, idim, ...
      nStress, iStress, dxcell, xcell, dxcell_vec, I, J);
%
    disp(sprintf( ...
      '%11.4f % 2i % 2i % 2i %2i %1i  %5.4e   %5.4e  %5.4e  %5.4e', ...
      Time, is_PD, is_NS, Method_used, M_lambda, is_Soln, ...
      mean(mean(abs(b_p_Rel(:,1:2)))), ...
      (diag(stress)(1:2))', stress(1,2) ))
%
%   if Time > 9745
%     istep, start_Time, lap_Time
%   end
%
%   check whether the simulation has reached the end of the current control
%   period, so that a new set of control parameters must be used
    if Change_Control_alt(istep, igoal, increment, max_increments, ...
                          Time, lap_Time, start_Time)
      disp(cstrcat('Finished with control period ',int2str(istep)))
%
%     get the next set of loading parameters
      [istep, icont, ddef, ddefm, dstress, stress_target, ...
       Reset_target_stress, ...
       istop, increment, max_increments, nStress, iStress, ...
       lap_Time, start_Time] = ...
      Control_alt(istep, icontr, icont, defrat, igoal, finalv, idim, ...
                  I, J, Time);
    end
%
    if istep >= size(icontr,1) + 1
      Time_to_Stop = 1;
    end
%
  end % while istep < size(icontr,1)
%
%page_screen_output(0);
%page_screen_output(1);
page_output_immediately(0);
