function [lambda0, n_intersect_lambda] = ...
         HeadStart( ...
           lambda, isHeadStart, ...
           Map_p_Rel_to_All_old, Map_p_Rel_to_All, ...
           V_pq_old, V_pq, C_pq_old, C_pq, ...
           map_lambda_to_pq_and_qp_old, map_lambda_to_pq_and_qp)
%
% this function uses the solution "lambda" of the previous time step
% to find the initial trial value of "lambda" for the current time step.
% Note that the lambdas can refer to different contacts in the two 
% time steps
%
  M_lambda = size(map_lambda_to_pq_and_qp,1);
%
  if isHeadStart && M_lambda>3
    [C, IA, IB] = ...
      intersect( ...
       [Map_p_Rel_to_All_old(V_pq_old(map_lambda_to_pq_and_qp_old(:,1),1))', ...
        Map_p_Rel_to_All_old(V_pq_old(map_lambda_to_pq_and_qp_old(:,1),2))', ...
        C_pq_old(map_lambda_to_pq_and_qp_old(:,1))], ...
       ...
       [Map_p_Rel_to_All(V_pq(map_lambda_to_pq_and_qp(:,1),1))', ...
        Map_p_Rel_to_All(V_pq(map_lambda_to_pq_and_qp(:,1),2))', ...
        C_pq(map_lambda_to_pq_and_qp(:,1))], ...
       'rows');
%
    n_intersect_lambda = length(IA);
    lambda0 = zeros(size(map_lambda_to_pq_and_qp,1),1);
    lambda0(IB) = lambda(IA);
%
  else
%   ignore the values of "lambda" in the previous time step
    lambda0 = [];
    n_intersect_lambda = 0;
  end
