function [ lupdate, iupdat] = ...
         Update_Near_Neighbors2( ...
           iupdat, iupdtm, istep, Time, idim, ...
           u, u_update, xcell, xcell_update, Threshold_separation, ...
           nbins, bin_list, surround_bins)
%
% this function determines whether a new near-neighbor search should be done.
% Near-neighbor searches are done by the function Near_Neighbors(), but these
% search take a lot of time. We attempt to do these near-neighbor searches
% sparingly
%
%----------------- INPUT ----------------
% iupdat = the number of increments since the last near-neighbor search
% iupdtm = a vector that gives the maximum number of increments before
%          a near-neighbor is conducted for a given istep control step.  
%          iupdtm given by the input RunFile.
% istep =  the current control step
%
%----------------- OUTPUT ---------------
% lupdate = Boolean scalar, whether to conduct a new near-neighbor search
% iupdat =  update value of iupdat
%
  iupdat = iupdat + 1;
%
% if this is the first increment in the simulation, or iupdat has attained
% iupdtm
  lupdate =    (istep==1 && Time==1) ...
            || (iupdat >= iupdtm);
%
% if the iupdat criterion is not met, check whether the criterion of particle
% movements is met
  if ~lupdate
    du = u - u_update;
    dxcell = xcell - xcell_update;
%
    if idim==2
%
%     minimum (negative) and maximum particle movements within each bin
      min_Mov_bin = zeros(nbins(1), nbins(2), 2);
      max_Mov_bin = zeros(nbins(1), nbins(2), 2);
%
%     min/max movements of particles in the various bins
      for i = 1:nbins(1)
        for j = 1:nbins(2)
%         minimum movements of all particles that are in bin i,j,k
          min_Move_bin(i,j, 1) = min(du(bin_list{i,j}, 1));
          min_Move_bin(i,j, 2) = min(du(bin_list{i,j}, 2));
%
%         maximum movements of all particles that are in bin i,j,k
          max_Move_bin(i,j, 1) = max(du(bin_list{i,j}, 1));
          max_Move_bin(i,j, 2) = max(du(bin_list{i,j}, 2));
        end
      end
%
%     the relative directions of surrounding bins in the two directions
      rel_bins = [-1, -1;
                  -1,  0;
                  -1,  1;
                   0, -1;
                   0,  0;
                   0,  1;
                   1, -1;
                   1,  0;
                   1,  1];
%
%     crossings of surrounding bins accross periodic cell boundaries: -1, 0 or 1
%     Taken relative to the center bin
      xcell_bins = zeros(nbins(1), nbins(2), 9, 2);
%
      for bin1 = 1:nbins(1)
        for bin2 = 1:nbins(2)
            xcell_bins(bin1, bin2, ...
                   find(surround_bins{bin1, bin2}(:,1) - bin1 + 1 < -1), 1) = 1;
            xcell_bins(bin1, bin2, ...
                   find(surround_bins{bin1, bin2}(:,1) - bin1 + 1 >  1), 1) =-1;
            xcell_bins(bin1, bin2, ...
                   find(surround_bins{bin1, bin2}(:,2) - bin2 + 1 < -1), 2) = 1;
            xcell_bins(bin1, bin2, ...
                   find(surround_bins{bin1, bin2}(:,2) - bin2 + 1 >  1), 2) =-1;
        end
      end
%
%     size of the arrays that gives the max and minimum movements of the 
%     particles within their bins
      Size_min_Move_bin = size(min_Move_bin);
      Size_max_Move_bin = size(max_Move_bin);
%
%     rows of 9x2 matrix that gives the locations of the surrounding bins
%     relative to a central bin
      Bins1 = zeros(3,2); Bins2 = zeros(3,2);  % 9,3 for 3D
      Bins1(:,1) = find(rel_bins(:,1)== 1);  % surrounding bins to the right
      Bins2(:,1) = find(rel_bins(:,1)==-1);  % surrounding bins to the left
      Bins1(:,2) = find(rel_bins(:,2)== 1);  % surrounding bins above
      Bins2(:,2) = find(rel_bins(:,2)==-1);  % surrounding bins below
%
%     find the maximum relative movements among particles in adjoining bins
      bin = 0;
      max_Approach_rel = zeros(nbins(1)*nbins(2),2);
%
      for bin1 = 1:nbins(1)
        for bin2 = 1:nbins(2)
%         for bin3 = 1:nbins(3)
            bin = bin + 1;
            Surround_bins = surround_bins{bin1, bin2} + 1;
%
%           maximum approach of surrounding cells on the right and left
            max_Approach_rel(bin,1) = ...
              max( ...
                  max_Move_bin(bin1, bin2, 1) ...
                  - min(min_Move_bin(sub2ind(Size_min_Move_bin, ...
                                             Surround_bins(Bins1(:,1),1)', ...
                                             Surround_bins(Bins1(:,1),2)', ...
                                             1 * ones(1,3) ...
                                             ))' ...
                         + dxcell(1,1) ...
                           *squeeze(xcell_bins(bin1, bin2, Bins1(:,1), 1))) ...
                  , ...
                  -min_Move_bin(bin1, bin2, 1) ...
                  + max(max_Move_bin(sub2ind(Size_max_Move_bin, ...
                                             Surround_bins(Bins2(:,1),1)', ...
                                             Surround_bins(Bins2(:,1),2)', ...
                                             1 * ones(1,3) ...
                                             ))' ...
                         + dxcell(1,1) ...
                           *squeeze(xcell_bins(bin1, bin2, Bins2(:,1), 1))) ...
              );
%
%           maximum approach of surrounding cells on the top and bottom
            max_Approach_rel(bin,2) = ...
              max( ...
                  max_Move_bin(bin1, bin2, 2) ...
                  - min(min_Move_bin(sub2ind(Size_min_Move_bin, ...
                                             Surround_bins(Bins1(:,2),1)', ...
                                             Surround_bins(Bins1(:,2),2)', ...
                                             2 * ones(1,3) ...
                                             ))' ...
                         + dxcell(2,2) ...
                           *squeeze(xcell_bins(bin1, bin2, Bins1(:,2), 2))) ...
                  , ...
                  -min_Move_bin(bin1, bin2, 2) ...
                  + max(max_Move_bin(sub2ind(Size_max_Move_bin, ...
                                             Surround_bins(Bins2(:,2),1)', ...
                                             Surround_bins(Bins2(:,2),2)', ...
                                             2 * ones(1,3) ...
                                             ))' ...
                         + dxcell(2,2) ...
                           *squeeze(xcell_bins(bin1, bin2, Bins2(:,2), 2))) ...
              );
%
%         end
        end
      end
%
    elseif idim==3
%
%     minimum (negative) and maximum particle movements within each bin
      min_Mov_bin = zeros(nbins(1), nbins(2), nbins(3), 3);
      max_Mov_bin = zeros(nbins(1), nbins(2), nbins(3), 3);
%
%     min/max movements of particles in the various bins
      for i = 1:nbins(1)
        for j = 1:nbins(2)
          for k = 1:nbins(3)
%           minimum movements of all particles that are in bin i,j,k
            min_Move_bin(i,j,k, 1) = min(du(bin_list{i,j,k}, 1));
            min_Move_bin(i,j,k, 2) = min(du(bin_list{i,j,k}, 2));
            min_Move_bin(i,j,k, 3) = min(du(bin_list{i,j,k}, 3));
%
%           maximum movements of all particles that are in bin i,j,k
            max_Move_bin(i,j,k, 1) = max(du(bin_list{i,j,k}, 1));
            max_Move_bin(i,j,k, 2) = max(du(bin_list{i,j,k}, 2));
            max_Move_bin(i,j,k, 3) = max(du(bin_list{i,j,k}, 3));
          end
        end
      end
%
%     the relative directions of surrounding bins in the three directions
      rel_bins = [-1, -1, -1;
                  -1,  0, -1;
                  -1,  1, -1;
                   0, -1, -1;
                   0,  0, -1;
                   0,  1, -1;
                   1, -1, -1;
                   1,  0, -1;
                   1,  1, -1;
                  -1, -1,  0;
                  -1,  0,  0;
                  -1,  1,  0;
                   0, -1,  0;
                   0,  0,  0;
                   0,  1,  0;
                   1, -1,  0;
                   1,  0,  0;
                   1,  1,  0;
                  -1, -1,  1;
                  -1,  0,  1;
                  -1,  1,  1;
                   0, -1,  1;
                   0,  0,  1;
                   0,  1,  1;
                   1, -1,  1;
                   1,  0,  1;
                   1,  1,  1];
%
%     crossings of surrounding bins accross periodic cell boundaries: -1, 0 or 1
%     Taken relative to the center bin
      xcell_bins = zeros(nbins(1), nbins(2), nbins(3), 27, 3);
%
      for bin1 = 1:nbins(1)
        for bin2 = 1:nbins(2)
          for bin3 = 1:nbins(3)
            xcell_bins(bin1, bin2, bin3, ...
             find(surround_bins{bin1, bin2, bin3}(:,1) - bin1 + 1 < -1), 1) = 1;
            xcell_bins(bin1, bin2, bin3, ...
             find(surround_bins{bin1, bin2, bin3}(:,1) - bin1 + 1 >  1), 1) =-1;
            xcell_bins(bin1, bin2, bin3, ...
             find(surround_bins{bin1, bin2, bin3}(:,2) - bin2 + 1 < -1), 2) = 1;
            xcell_bins(bin1, bin2, bin3, ...
             find(surround_bins{bin1, bin2, bin3}(:,2) - bin2 + 1 >  1), 2) =-1;
            xcell_bins(bin1, bin2, bin3, ...
             find(surround_bins{bin1, bin2, bin3}(:,3) - bin3 + 1 < -1), 3) = 1;
            xcell_bins(bin1, bin2, bin3, ...
             find(surround_bins{bin1, bin2, bin3}(:,3) - bin3 + 1 >  1), 3) =-1;
          end
        end
      end
%
%     size of the arrays that gives the max and minimum movements of the 
%     particles within their bins
      Size_min_Move_bin = size(min_Move_bin);
      Size_max_Move_bin = size(max_Move_bin);
%
%     rows of 9x2 matrix that gives the locations of the surrounding bins
%     relative to a central bin
      Bins1 = zeros(9,3); Bins2 = zeros(9,3);
      Bins1(:,1) = find(rel_bins(:,1)== 1);  % surrounding bins to the right
      Bins2(:,1) = find(rel_bins(:,1)==-1);  % surrounding bins to the left
      Bins1(:,2) = find(rel_bins(:,2)== 1);  % surrounding bins above
      Bins2(:,2) = find(rel_bins(:,2)==-1);  % surrounding bins below
      Bins1(:,3) = find(rel_bins(:,3)== 1);  % surrounding bins in front
      Bins2(:,3) = find(rel_bins(:,3)==-1);  % surrounding bins behind
%
%     find the maximum relative movements among particles in adjoining bins
      bin = 0;
      max_Approach_rel = zeros(nbins(1)*nbins(2)*nbins(3),3);
%
      for bin1 = 1:nbins(1)
        for bin2 = 1:nbins(2)
          for bin3 = 1:nbins(3)
            bin = bin + 1;
            Surround_bins = surround_bins{bin1, bin2, bin3} + 1;
%
%           maximum approach of surrounding cells on the right and left
            max_Approach_rel(bin,1) = ...
              max( ...
                  max_Move_bin(bin1, bin2, bin3, 1) ...
                  - min(min_Move_bin(sub2ind(Size_min_Move_bin, ...
                                             Surround_bins(Bins1(:,1),1)', ...
                                             Surround_bins(Bins1(:,1),2)', ...
                                             Surround_bins(Bins1(:,1),3)', ...
                                             1 * ones(1,9) ...
                                             ))' ...
                      + dxcell(1,1) ...
                      *squeeze(xcell_bins(bin1, bin2, bin3, Bins1(:,1), 1))) ...
                  , ...
                  -min_Move_bin(bin1, bin2, bin3, 1) ...
                  + max(max_Move_bin(sub2ind(Size_max_Move_bin, ...
                                             Surround_bins(Bins2(:,1),1)', ...
                                             Surround_bins(Bins2(:,1),2)', ...
                                             Surround_bins(Bins2(:,1),3)', ...
                                             1 * ones(1,9) ...
                                             ))' ...
                      + dxcell(1,1) ...
                      *squeeze(xcell_bins(bin1, bin2, bin3, Bins2(:,1), 1))) ...
              );
%
%           maximum approach of surrounding cells on the top and bottom
            max_Approach_rel(bin,2) = ...
              max( ...
                  max_Move_bin(bin1, bin2, bin3, 2) ...
                  - min(min_Move_bin(sub2ind(Size_min_Move_bin, ...
                                             Surround_bins(Bins1(:,2),1)', ...
                                             Surround_bins(Bins1(:,2),2)', ...
                                             Surround_bins(Bins1(:,2),3)', ...
                                             2 * ones(1,9) ...
                                             ))' ...
                      + dxcell(2,2) ...
                      *squeeze(xcell_bins(bin1, bin2, bin3, Bins1(:,2), 2))) ...
                  , ...
                  -min_Move_bin(bin1, bin2, bin3, 2) ...
                  + max(max_Move_bin(sub2ind(Size_max_Move_bin, ...
                                             Surround_bins(Bins2(:,2),1)', ...
                                             Surround_bins(Bins2(:,2),2)', ...
                                             Surround_bins(Bins2(:,2),3)', ...
                                             2 * ones(1,9) ...
                                             ))' ...
                      + dxcell(2,2) ...
                      *squeeze(xcell_bins(bin1, bin2, bin3, Bins2(:,2), 2))) ...
              );
%
%           maximum approach of surrounding cells in front and behind
            max_Approach_rel(bin,3) = ...
              max( ...
                  max_Move_bin(bin1, bin2, bin3, 3) ...
                  - min(min_Move_bin(sub2ind(Size_min_Move_bin, ...
                                             Surround_bins(Bins1(:,3),1)', ...
                                             Surround_bins(Bins1(:,3),2)', ...
                                             Surround_bins(Bins1(:,3),3)', ...
                                             3 * ones(1,9) ...
                                             ))' ...
                      + dxcell(3,3) ...
                      *squeeze(xcell_bins(bin1, bin2, bin3, Bins1(:,3), 3))) ...
                  , ...
                  -min_Move_bin(bin1, bin2, bin3, 3) ...
                  + max(max_Move_bin(sub2ind(Size_max_Move_bin, ...
                                             Surround_bins(Bins2(:,3),1)', ...
                                             Surround_bins(Bins2(:,3),2)', ...
                                             Surround_bins(Bins2(:,3),3)', ...
                                             3 * ones(1,9) ...
                                             ))' ...
                      + dxcell(3,3) ...
                      *squeeze(xcell_bins(bin1, bin2, bin3, Bins2(:,3), 3))) ...
              );
          end
        end
      end
%
    end % if idim==3
%
%   maximum approach between particles in adjacent cells
    max_Approach = max(max(max_Approach_rel));
%
    if max_Approach > Threshold_separation
      lupdate = 1;
    end
%
  end % if ~lupdate
%
